// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attendance_monitoring.Data;

#nullable disable

namespace attendance_monitoring.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204030000_AddUserStatusFilterToGetAllUsersSP")]
    partial class AddUserStatusFilterToGetAllUsersSP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a stored procedure migration, no model changes
        }
    }
}
