// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attendance_monitoring.Data;

#nullable disable

namespace attendance_monitoring.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102033712_MakeStudentNamesRequired")]
    partial class MakeStudentNamesRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This designer file is auto-generated and represents the database model
            // after the MakeStudentNamesRequired migration is applied.
            // The actual model building is inherited from ApplicationDbContextModelSnapshot.
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
