using attendance_monitoring.Classes;
using attendance_monitoring.Models.Request;
using attendance_monitoring.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Authorization;

namespace attendance_monitoring.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class StudentController : ControllerBase
{
    private readonly IStudentRepository _studentRepository;

    public StudentController(IStudentRepository studentRepository)
    {
        _studentRepository = studentRepository;
    }

    // GET: api/Student
    [HttpGet]
    public async Task<ActionResult<IEnumerable<Student>>> GetStudents([FromQuery] PaginationQuery paginationQuery)
    {
        var students = await _studentRepository.GetAllStudentsAsync(paginationQuery);
        return Ok(students);
    }

    // GET: api/Student/5
    [HttpGet("{id}")]
    public async Task<ActionResult<Student>> GetStudent(int id)
    {
        var student = await _studentRepository.GetStudentByIdAsync(id);

        if (student == null)
        {
            return NotFound();
        }

        return Ok(student);
    }
    
    // POST: api/Students/
    [HttpPost("")]
    public async Task<ActionResult<Student>> CreateStudent(CreateStudent createStudent)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        // Create student with timestamps (ID will be generated by DB)
        var student = new Student
        {
            Firstname = createStudent.Firstname,
            Lastname = createStudent.Lastname,
            Email = createStudent.Email,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        var data = await _studentRepository.CreateStudent(student);
        
        // Save changes to the database
        await _studentRepository.SaveChangesAsync();
        
        return CreatedAtAction(nameof(GetStudent), new { id = data.Id }, data);
    }
}